// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Retorna uma string \"Hello, i am Golang Websocket Server!\"",
                "tags": [
                    "health check"
                ],
                "summary": "Mostra uma mensagem de hello",
                "responses": {
                    "200": {
                        "description": "Hello, i am Golang Websocket Server!",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ws": {
            "get": {
                "description": "Estabelece uma conexão WebSocket com a sala especificada",
                "tags": [
                    "websocket"
                ],
                "summary": "Conexão Websocket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nome da sala",
                        "name": "room",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nome do usuário",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
